name: 69 - Run on push to rc

on:
  push:
    branches:
      - 'rc/*.*.*'

jobs:
  release-candidate-tag:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag.outputs.tag }}
    steps:
      - name: Extract branch tag if necessary
        id: tag
        run: |
          BRANCH=${{ github.head_ref }}
          TAG="${BRANCH//rc\//""}"
          echo $TAG
          echo "tag=$TAG" >> $GITHUB_OUTPUT

  release:
    needs:
      - release-candidate-tag
    runs-on: ubuntu-latest
    env:
      TAG: ${{ needs.release-candidate-tag.outputs.tag }}
    steps:
      - name: echo TAG
        run: Echo ${{ env.TAG }}
