name: Test 84 # Related to SO question https://stackoverflow.com/questions/76588045/github-workflow-confused-about-tojson-and-fromjson-im-doing-a-json-ouput-and

on: 
  push:

jobs:
  matrix:
    runs-on: ubuntu-latest
    name: Setup
    outputs:
        php-versions: ["7.4.10", "5.6.13", "7.4.33", "8.1"]
    steps:
      - run: echo TEST

  build:
    runs-on: ubuntu-latest
    needs: matrix
    strategy:
      fail-fast: false
      matrix:
        version: ${{ fromJson(needs.matrix.outputs.php-versions) }}
    steps:
      - run: echo ${{ matrix.version }}
