name: Test 87

on:
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy-infra:
    name: StackSpot Runtime Infra Debian (v1)
    runs-on: ubuntu-latest
    container:
      image: docker://stackspot/stk-cli-debian:5.4.7
    steps:
      - name: Show STK CLI version (1)
        continue-on-error: true
        run: $HOME/.stk/bin/stk --version
      - name: Show STK CLI version (2)
        continue-on-error: true
        run: stk --version


  deploy-infra-ubuntu:
    name: StackSpot Runtime Infra Ubuntu (v1)
    runs-on: ubuntu-latest
    container:
      image: docker://stackspot/stk-cli-ubuntu:5.4.7
    steps:
      - name: Show STK CLI version (1)
        continue-on-error: true
        run: $HOME/.stk/bin/stk --version
      - name: Show STK CLI version (2)
        continue-on-error: true
        run: stk --version

  deploy:
    name: StackSpot Runtime Infra Debian (v1)
    runs-on: ubuntu-latest
    steps:
      - name: Show STK CLI version (1)
        continue-on-error: true
        run: docker run stackspot/stk-cli-debian:5.4.7 --version

  test:
    name: StackSpot Runtime Infra Debian (v1)
    runs-on: ubuntu-latest
    container:
      image: docker://stackspot/stk-cli-debian:5.4.7
    steps:
      - name: Show STK CLI  version
        run: --version