name: Test 75 # Related to https://stackoverflow.com/questions/75446952/github-workflows-changing-or-specifying-environment-variables-in-matrix-jobs

on:
  push:

env:
  MY_VAR: One

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - MY_VAR: Two
          - MY_VAR: Three
    steps:
      - run: |
          echo "$MY_VAR"
          echo ${{ matrix.MY_VAR }}