name: Test 95 # Related to SO https://stackoverflow.com/questions/78461104/how-can-i-configure-a-github-actions-strategy-matrix-to-dynamically-read-a-json

on:
  workflow_dispatch:
    inputs:
      stsReplay:
        description: 'team to pick'
        required: true
        default: 'real-madrid'
        type: choice
        options:
          - 'manu'
          - 'chelsea'
          - 'real-madrid'
          - 'fc-barcelona'
          - 'bayern'
          - 'ac-milan'

env:
  REPLAY_MAP_JSON: |
    {
      "manu": ["casemiro","dalot","rashford"],
      "chelsea": ["sterling","james","silva"],
      "real-madrid": ["vini-jr","modric","kroos"],
      "bayern": ["sane","kane","alphonso"],
      "ac-milan": ["rafael-leao","giroud","pulisic"]
    }

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      values: ${{ steps.set-matrix.outputs.values }}
    steps:
      - id: set-matrix
        run: |
          # Initialize an empty array
          myArray=()

          # Get the array associated with the current key
          players=$(jq -r '."${{ inputs.stsReplay }}"[]' <<< "$REPLAY_MAP_JSON")
          # Add each player to myArray
          while IFS= read -r player; do
              myArray+=("\"$player\"")
          done <<< "$players"
          # Convert myArray to a JSON array using jq
          myArray=$(jq --compact-output --null-input '$ARGS.positional' --args -- "${myArray[@]}")
          # Output the updated tasks list
          echo "Updated tasks list: $myArray"
          echo "values=$myArray" >> "$GITHUB_OUTPUT"
  
  job2:
    needs: job1
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ needs.job1.outputs.values }}
    steps:
      - run: echo "Player ${{ matrix}}"

  job3:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo OUTPUT ${{ needs.job1.outputs.values }}
          echo JSON OUTPUT ${{ fromJSON(needs.job1.outputs.values) }}