name: Test 78 # Related to https://stackoverflow.com/questions/75720251/setup-environment-to-use-variable-context-when-calling-a-reusable-workflow

on:
  workflow_call:
    # Map the workflow outputs to job outputs
    outputs:
      project-id:
        description: "description"
        type: string
      environment:
        description: "environment"
        type: string
      cluster-name:
        description: "cluster name"
        type: string
      region:
        description: "region"
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "${{ inputs.project-id }}"
          echo "${{ inputs.environment }}"
          echo "${{ inputs.cluster-name }}"
          echo "${{ inputs.region }}"