name: Test 85 # Related to SO question https://stackoverflow.com/questions/76586717/github-actions-how-to-trigger-a-reusable-workflow-by-condition-of-a-matrix-valu
on: 
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      versions: ${{ steps.array.outputs.array }}
    steps:
      - id: array
        run: |
          myArray=()
          if [ "true" = "true" ] # some condition
          then
            myArray+=("7.4.10")
          fi
          if [ "true" = "true" ] # some condition
          then
            myArray+=("5.6.13")
          fi
          if [ "true" = "true" ] # some condition
          then
            myArray+=("7.4.33")
          fi
          if [ "true" = "true" ] # some condition
          then
            myArray+=("8.1")
          fi
          myArray=$(jq --compact-output --null-input '$ARGS.positional' --args -- "${myArray[@]}")
          echo "Updated array list: $myArray"
          echo "array=$myArray" >> $GITHUB_OUTPUT
        shell: bash

  build:
    runs-on: ubuntu-latest
    needs: [setup]
    strategy:
      fail-fast: false
      matrix:
        version: ${{ fromJSON(needs.setup.outputs.versions) }}
    if: ${{ matrix.version == '8.1 }}
    steps:
      - run: echo ${{ matrix.version }}
